name: hooks_riverpod_sk
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.2


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  json_serializable: ^6.3.1

flutter:

  uses-material-design: true

  assets:
    - images/gg.png
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Paper
      fonts:
        - asset: fonts/Paper.otf
          style: normal
    - family: My
      fonts:
        - asset: fonts/15310.otf
          style: normal

