name: flutter_getx
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 
  get:
  provider:
  json_serializable: ^6.5.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - images/gg.png

  fonts:
    - family: Paper
      fonts:
        - asset: fonts/Paper.otf
          style: normal
    - family: My
      fonts:
        - asset: fonts/15310.otf
          style: normal
    - family: Vetka
      fonts:
        - asset: fonts/Vetka.otf
          style: normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
